version: '3'

services:
  database:
    build:
      context: .
      dockerfile: Dockerfile_ronfic_main    
    image: ronfic_main_dev_image:latest
    container_name: ronfic_main_dump_db
    environment:
      POSTGRES_DB : ronfic_main
      POSTGRES_USER : ronfic
      POSTGRES_PASSWORD : ronfic_2024
    ports:
      - "5432:5432"
    volumes:
      - ./restore.sql:/docker-entrypoint-initdb.d/01_restore_data.sql      
      - ./separate_table_ddl.sql:/docker-entrypoint-initdb.d/02_create_ddl.sql      
    restart: always

